use assignment01;

select FIRST_NAME AS WORKER_NAME from worker;

select upper(FIRST_NAME) AS FIRST_NAME from worker;

select distinct DEPARTMENT from worker;

select substring(FIRST_NAME,1,3) from worker;

select instr(FIRST_NAME,BINARY'a') from worker where FIRST_NAME='Amitabh';

select RTRIM(FIRST_NAME) from worker;

select LTRIM(DEPARTMENT) from worker;

select distinct length(DEPARTMENT) from worker;

SELECT REPLACE(FIRST_NAME,'a','A') FROM worker;

SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS COMPLETE_NAME FROM worker;

SELECT *FROM (SELECT * FROM WORKER ORDER BY FIRST_NAME)FNAME ORDER BY FNAME.DEPARTMENT DESC;

SELECT * FROM worker WHERE FIRST_NAME="VIPUL" OR FIRST_NAME="SATISH";

SELECT * FROM worker WHERE FIRST_NAME !="Vipul" AND FIRST_NAME !="Satish";

SELECT * FROM worker WHERE DEPARTMENT="Admin";

SELECT * FROM worker WHERE FIRST_NAME LIKE "a%";

SELECT * FROM worker WHERE FIRST_NAME LIKE "%a";

SELECT * FROM worker WHERE FIRST_NAME LIKE "%h" and length(FIRST_NAME)=6;

SELECT * FROM worker WHERE SALARY >=100000 AND SALARY<=500000;

SELECT * FROM worker WHERE JOINING_DATE LIKE "2014-02%";

SELECT COUNT(DEPARTMENT)FROM worker WHERE DEPARTMENT="Admin";

SELECT * FROM worker WHERE SALARY>=500000 OR SALARY<=100000;

SELECT COUNT(WORKER_ID),DEPARTMENT FROM worker GROUP BY DEPARTMENT ORDER BY DEPARTMENT DESC;

SELECT * FROM worker W,title T WHERE W.WORKER_ID=T.WORKER_REF_ID AND T.WORKER_TITLE="MANAGER";

SELECT * FROM title T,(SELECT COUNT(WORKER_REF_ID),WORKER_TITLE FROM TITLE GROUP BY WORKER_TITLE HAVING COUNT(WORKER_REF_ID)=1) W WHERE T.WORKER_TITLE=W.WORKER_TITLE;

SELECT * FROM worker WHERE MOD(WORKER_ID,2)<>0;

SELECT * FROM WORKER WHERE MOD(WORKER_ID,2)=0;

CREATE TABLE WORKER_CLONE SELECT * FROM worker;
SELECT * FROM WORKER_CLONE;

SELECT * FROM worker JOIN bonus ON WORKER.WORKER_ID=BONUS.WORKER_REF_ID;

SELECT * FROM worker WHERE WORKER_ID NOT IN(SELECT WORKER_REF_ID FROM bonus);